# Generated by Django 2.2.4 on 2019-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('x_pos', models.FloatField(default=0.0)),
                ('y_pos', models.FloatField(default=0.0)),
                ('num', models.FloatField(blank=True, default=0)),
                ('creator', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
