# Generated by Django 2.2.4 on 2019-10-24 20:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='links',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), blank=True, max_length=4500, size=150),
        ),
    ]
