# Generated by Django 2.2.4 on 2019-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_block', models.IntegerField(default=0)),
                ('ending_block', models.IntegerField(default=0)),
                ('creator', models.CharField(default='', max_length=100)),
                ('num', models.IntegerField(default=0)),
                ('start_x', models.FloatField(default=0)),
                ('start_y', models.FloatField(default=0)),
                ('end_x', models.FloatField(default=0)),
                ('end_y', models.FloatField(default=0)),
            ],
        ),
    ]
